-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, (SUM(B.PRICE * SALES.SALES)) AS TOTAL_SALES
FROM AUTHOR A
LEFT JOIN BOOK B ON A.AUTHOR_ID = B.AUTHOR_ID
LEFT JOIN BOOK_SALES SALES ON B.BOOK_ID = SALES.BOOK_ID
WHERE SALES.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC