-- 코드를 입력하세요
SELECT CART_ID
FROM (
    SELECT CART_ID,
        CASE WHEN NAME = 'Milk' THEN 1
        ELSE 0 END AS MILK_YN,
        CASE WHEN NAME = 'Yogurt' THEN 1
        ELSE 0 END AS YOGURT_YN
    FROM CART_PRODUCTS)
GROUP BY CART_ID
HAVING SUM(MILK_YN) >= 1 AND SUM(YOGURT_YN) >= 1
ORDER BY CART_ID
;