-- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE,
    (daily_fee * 30) * (100 - (
        SELECT DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
        WHERE DP.CAR_TYPE = CC.CAR_TYPE AND DP.DURATION_TYPE = '30일 이상')) * 0.01 AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
WHERE CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-11' BETWEEN TO_CHAR(START_DATE, 'YYYY-MM') AND TO_CHAR(END_DATE, 'YYYY-MM'))
AND (daily_fee * 30) * (100 - (
        SELECT DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
        WHERE DP.CAR_TYPE = CC.CAR_TYPE AND DP.DURATION_TYPE = '30일 이상')) * 0.01
        BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
;