-- 코드를 입력하세요
SELECT GB.TITLE, GB.BOARD_ID, GR.REPLY_ID, GR.WRITER_ID, GR.CONTENTS, TO_CHAR(GR.CREATED_DATE, 'yyyy-mm-dd') AS CREATED_DATE
FROM USED_GOODS_BOARD GB
JOIN USED_GOODS_REPLY GR
ON GB.BOARD_ID = GR.BOARD_ID
WHERE TO_CHAR(GB.CREATED_DATE, 'yyyy-mm-dd') LIKE '2022-10-%'
ORDER BY GR.CREATED_DATE, GB.TITLE;